### ISSUE TITLE
Adding Language pair

### ISSUE THREAD

**Issue by siddhantjain07** [apertium/apertium-staging#2]
Hello,
I went through the Apertium Translation website its looks good but had many language pairs missing.
If allowed can I add a language pair English-Italian and vise-versa?

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/apertium-eng-ita exists but just isn't release quality yet. It's live on https://beta.apertium.org/ though.

You're welcome to improve eng-ita. Come to IRC Freenode #apertium if you want help.
